# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131f8a28a6051a349c36e41df1315ff588fba39c0bf8303ba5b4670a9f5811b2582ddaca75d57ed85b1adee0ed3014b9202f1d7f5bd917e292f23275007bad82

test:
  secret_key_base: 0f349b51b2d0bafaa967b8d838cb6edb88728a594053e24045e091affc986f373cdca07c6e0c58868cadd820b85559fb710d59c0d024c55aa53cdc2a07774fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
